baseURL = "https://crisbh.github.io/numerical-relativity-intro/"
languageCode = "es"
title = "Introducción a la Relatividad Numérica"
theme = "book"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "dracula"

[[menu.after]]
    name = "📖 Clases"
    url = "/slides/"
    weight = 5

