baseURL = "https://crisbh.github.io/numerical-relativity-intro/"
languageCode = "es"
title = "Relatividad Numérica"
theme = "relearn"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "dracula"

